# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y_WEwEQBQadbm6yDxUdG71gLssGM5ern
"""

# Comando "input" para coletar dados do usuário.

nome = input("digite seu nome: ")
print("Olá" , nome , ", seja bem-vindo(a)!")

# Comando "float" para números reais.
num1 = float(input("selecione o primeiro número: "))
operaçao = input("selecione a operação ")
num2 = float(input("selecione o segundo número: "))

# Comando "if", "elif" e "else" para definir quando aplicar as operações.
if operaçao == "+":
    print("o resultado é" , num1 + num2)
elif operaçao == "-":
    print("o resultado é" , num1 - num2)
elif operaçao == "*":
    print("o resultado é" , num1 * num2)
elif operaçao == "/":
    print("o resultado é" , num1 / num2)
else:
     print("operação inválida")